-- Akif CPG — initial schema for the shared cloud workspace.
--
-- Design notes worth knowing before you change anything here:
--
-- * Ids stay TEXT and are generated by the browser (crypto.randomUUID, plus
--   fixed ids for the shipped examples like 'example-godiva-sticks'). Those
--   fixed ids would collide between workspaces, so every table is keyed on
--   (workspace_id, id) rather than id alone.
-- * Money and rates stay TEXT, matching the app: every value is a raw form
--   string and '' is the "unset" marker. A numeric column would round-trip ''
--   wrongly and fight Decimal.js, which is the only thing allowed to do
--   arithmetic here.
-- * Nested app structures (basics, assumptions, promotions, audit history) are
--   JSONB. They are read and written whole by the client and never queried
--   field by field in SQL, so normalising them would buy nothing.
-- * Collections the UI shows in order carry created_at (products, scenarios,
--   profiles) or an explicit position (trade_spend_bands), because a table has
--   no inherent order and the app used to rely on array order.

create extension if not exists pgcrypto;

-- ── Tenancy ────────────────────────────────────────────────────────────────

create table workspaces (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  created_at timestamptz not null default now()
);

create table workspace_members (
  workspace_id uuid not null references workspaces (id) on delete cascade,
  user_id      uuid not null references auth.users (id) on delete cascade,
  role         text not null default 'editor' check (role in ('owner', 'editor', 'viewer')),
  created_at   timestamptz not null default now(),
  primary key (workspace_id, user_id)
);

-- SECURITY DEFINER on purpose, and it is not optional: the policy on
-- workspace_members itself calls this, so a plain function would recurse
-- through that table's own RLS. Definer rights read the membership row
-- directly. Empty search_path so nothing can be shadowed by a temp schema.
create function is_workspace_member(ws uuid) returns boolean
  language sql
  stable
  security definer
  set search_path = ''
as $$
  select exists (
    select 1 from public.workspace_members m
    where m.workspace_id = ws and m.user_id = auth.uid()
  );
$$;

-- ── Workspace data ─────────────────────────────────────────────────────────

create table products (
  workspace_id         uuid not null references workspaces (id) on delete cascade,
  id                   text not null,
  basics               jsonb not null,
  structure            text not null,
  route                text not null check (route in ('A', 'B', 'C', 'D', 'E')),
  cogs_mode            text not null check (cogs_mode in ('simple', 'detailed')),
  simple_cogs_per_unit text not null default '',
  cogs_components      jsonb not null default '[]'::jsonb,
  onboarding           jsonb,
  assumption_overrides jsonb,
  -- Data URL, capped client-side at 64K chars (lib/ui/logo.ts). The cap was a
  -- localStorage quota concern; it stays because it also keeps rows small.
  logo_data_url        text,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  primary key (workspace_id, id)
);

create table scenarios (
  workspace_id uuid not null references workspaces (id) on delete cascade,
  id           text not null,
  product_id   text not null,
  name         text not null,
  assumptions  jsonb not null,
  -- Append-only audit trail (PRD §68); values are preformatted for display and
  -- must never be reformatted later.
  history      jsonb not null default '[]'::jsonb,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  primary key (workspace_id, id),
  foreign key (workspace_id, product_id)
    references products (workspace_id, id) on delete cascade
);

create index scenarios_by_product on scenarios (workspace_id, product_id);

create table distributor_profiles (
  workspace_id          uuid not null references workspaces (id) on delete cascade,
  id                    text not null,
  name                  text not null,
  margin_basis          text not null check (margin_basis in ('margin', 'markup')),
  margin_rate           text not null default '',
  handling_fee_per_unit text not null default '',
  notes                 text not null default '',
  created_at            timestamptz not null default now(),
  primary key (workspace_id, id)
);

create table retailer_profiles (
  workspace_id                   uuid not null references workspaces (id) on delete cascade,
  id                             text not null,
  name                           text not null,
  channel                        text not null default '',
  -- '' means "buys direct". Deliberately not a foreign key: the empty string
  -- is a real value in the app, not a missing reference (PRD §47).
  default_distributor_profile_id text not null default '',
  retailer_margin_basis          text not null check (retailer_margin_basis in ('margin', 'markup')),
  retailer_margin_rate           text not null default '',
  broker_rate                    text not null default '',
  deductions_rate                text not null default '',
  trade_spend_rate               text not null default '',
  payment_terms                  text not null default '',
  notes                          text not null default '',
  created_at                     timestamptz not null default now(),
  primary key (workspace_id, id)
);

create table trade_spend_bands (
  workspace_id     uuid not null references workspaces (id) on delete cascade,
  id               text not null,
  -- Bands are a ladder; without this they would come back in whatever order
  -- Postgres felt like.
  position         integer not null,
  label            text not null,
  min_rate         text not null,
  -- NULL is meaningful: the open-ended top band (PRD §24).
  max_rate         text,
  guidance         text not null default '',
  -- NULL = informational only.
  advisor_priority text check (advisor_priority in ('critical', 'warning', 'opportunity')),
  primary key (workspace_id, id)
);

create table workspace_settings (
  workspace_id       uuid primary key references workspaces (id) on delete cascade,
  portfolio_settings jsonb not null
    default '{"redContributionBelow":"0","greenTargetTolerance":"0"}'::jsonb,
  -- One-time example bundles already delivered to THIS workspace
  -- (lib/scenario/seeds.ts). Per workspace, not per browser.
  applied_seeds      text[] not null default '{}'
);

-- Which product and scenario each person is looking at. Per user on purpose:
-- sharing it would make one person's product switch yank the other's screen.
create table user_ui_state (
  user_id                    uuid not null references auth.users (id) on delete cascade,
  workspace_id               uuid not null references workspaces (id) on delete cascade,
  active_product_id          text,
  active_scenario_by_product jsonb not null default '{}'::jsonb,
  primary key (user_id, workspace_id)
);

-- ── Row level security ─────────────────────────────────────────────────────
-- Nothing is readable or writable without a session that belongs to the
-- workspace. This, not the anon key, is the security boundary: the anon key
-- ships in the browser bundle by design.

alter table workspaces          enable row level security;
alter table workspace_members   enable row level security;
alter table products            enable row level security;
alter table scenarios           enable row level security;
alter table distributor_profiles enable row level security;
alter table retailer_profiles   enable row level security;
alter table trade_spend_bands   enable row level security;
alter table workspace_settings  enable row level security;
alter table user_ui_state       enable row level security;

create policy members_read_workspace on workspaces
  for select using (is_workspace_member(id));

create policy members_read_membership on workspace_members
  for select using (is_workspace_member(workspace_id));

-- Membership is managed in the dashboard, not by the app: no insert/update/
-- delete policy exists, so even a member cannot add somebody.

create policy members_rw_products on products
  for all using (is_workspace_member(workspace_id))
  with check (is_workspace_member(workspace_id));

create policy members_rw_scenarios on scenarios
  for all using (is_workspace_member(workspace_id))
  with check (is_workspace_member(workspace_id));

create policy members_rw_distributor_profiles on distributor_profiles
  for all using (is_workspace_member(workspace_id))
  with check (is_workspace_member(workspace_id));

create policy members_rw_retailer_profiles on retailer_profiles
  for all using (is_workspace_member(workspace_id))
  with check (is_workspace_member(workspace_id));

create policy members_rw_trade_spend_bands on trade_spend_bands
  for all using (is_workspace_member(workspace_id))
  with check (is_workspace_member(workspace_id));

create policy members_rw_workspace_settings on workspace_settings
  for all using (is_workspace_member(workspace_id))
  with check (is_workspace_member(workspace_id));

-- Your own view state only, even inside a shared workspace.
create policy own_ui_state on user_ui_state
  for all using (user_id = auth.uid())
  with check (user_id = auth.uid() and is_workspace_member(workspace_id));

-- ── Keep updated_at honest ─────────────────────────────────────────────────
-- Step 22 uses scenarios.updated_at to notice "someone else changed this
-- while you were editing", so the client must not be able to backdate it.

create function touch_updated_at() returns trigger
  language plpgsql
  set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger products_touch_updated_at
  before update on products
  for each row execute function touch_updated_at();

create trigger scenarios_touch_updated_at
  before update on scenarios
  for each row execute function touch_updated_at();
